### ISSUE TITLE
c1xx: fatal error C1083: 無法開啟來源檔案: 'pyzed/sl.cpp': No such file or directory error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by PeterParkerLogic** [stereolabs/zed-python-api#101]
when I run (python setup.py build) in windows10 ,python3.6.3, these errors come out. If some body know how to fix it, please tell me. Thanks

**Comment by Poutsh** [comment]
Hi @PeterParkerLogic 

Which version of the ZED SDK are you using?
Have you installed the python requirements ? https://github.com/stereolabs/zed-python-api#prerequisites
Have you tried installing the ZED Python API using pip ? https://github.com/stereolabs/zed-python-api#prerequisites
