### ISSUE TITLE
Memory leak in SVO reader

### ISSUE THREAD

**Issue by rbrigden** [stereolabs/zed-python-api#111]
We are reading a dataset of SVOs in a loop as part of a batch processing job and noticed a significant memory leak. In one specific application, we seek to random positions in the SVO before grabbing frames. In this case, memory usage grows unbounded at a rate of around 2.5 MBps until our host crashes.

Here is a plot of memory usage by a single process reading a set of SVOs (one at a time) and seeking to random frames in each SVO. 

![random_seeking](https://user-images.githubusercontent.com/11284030/68824287-33d2fa80-064b-11ea-90e3-34a9f39b373f.png)

We were able to reproduce this memory leak using a snippet from the `read_svo.py` example, although the memory does not leak as rapidly.

```python
import pyzed.sl as sl


def main():

    path = "/path/to/video.svo"
    print("Reading SVO file: {0}".format(path))

    init = sl.InitParameters(svo_input_filename=path ,svo_real_time_mode=False)
    cam = sl.Camera()
    status = cam.open(init)
    if status != sl.ERROR_CODE.SUCCESS:
        print(repr(status))
        exit()

    runtime = sl.RuntimeParameters()
    mat = sl.Mat()
    while True:  # for 'q' key
        err = cam.grab(runtime)
        if err == sl.ERROR_CODE.SUCCESS:
            cam.retrieve_image(mat)
        else:
            break
    cam.close()



if __name__ == "__main__":
    for _ in range(40):
        main()
```

Here is the memory usage by the process over time for the above program

![read_svo_mem_leak](https://user-images.githubusercontent.com/11284030/68824409-a04df980-064b-11ea-91ff-0857f380489d.png)

These programs are run with pyzed 2.8 on Ubuntu 18 using a RTX2080.

**Comment by adujardin** [comment]
Thank you for reporting this issue, we'll investigate and keep you posted.

**Comment by AlexanderKhazatsky** [comment]
Hello, im experiencing the same issue. Was this resolved?
