### ISSUE TITLE
Tracking pose different than ZEDfu

### ISSUE THREAD

**Issue by fgtoralesch** [stereolabs/zed-python-api#112]
I have recorded a video sequence with a ZED camera mounted on a car driving at 20 km/h and for my use case I want to use the poses/odometry to locate object detections on a map. Even on a relatively short drive I noticed a significant drift and some jumps, but the trajectory looks reasonably well. The interesting problem is that if I use ZEDfu to display the map and trajectory I see that the trajectory looks the same but much "smoother", i.e. without the jumps. 

I assume that this might be due to some bundle adjustment or another algorithm optimising the trajectory since I extract my poses after every "grab" event, i.e. online. However, since I'm using recordings, It would be very useful for my use case to retrieve a more accurate offline trajectory (or at least without jumps) as it seems ZEDfu is plotting. Is there any interface to access that smoother trajectory used for the offline spatial mapping? I couldn't find it by myself.

Thanks in advance.

Edit: I set the flag `tracking_parameters.enable_pose_smoothing = True` and certainly could get rid of the jumps. However, this smoothness also made the pose estimation be way worse than it was before. The sequence is just driving one street forward, turning around and driving back to the start position so when I say the error increased I mean that the trajectory is less "straight" as without smoothing and the start and end point end up being separated by a huge distance (an order of magnitude bigger) than the trajectory without smoothing

**Comment by IlanElfen** [comment]
Did you figure this out? I'm trying to retrieve the optimized camera pose from ZEDfu too
