### ISSUE TITLE
CUDA10.1 Not Supported

### ISSUE THREAD

**Issue by cm107** [stereolabs/zed-python-api#115]
After building from source and running tutorials/image_capture.py, I get the following error.
Traceback (most recent call last):
  File "image_capture.py", line 21, in <module>
    import pyzed.sl as sl
ImportError: libnppial.so.10.0: cannot open shared object file: No such file or directory

There is no libnppial.so.10.0 in my /usr/local/cuda/lib64 folder, but there is a libnppial.so.10.1.168, since I am using CUDA10.1. So I take it that CUDA10.1 is not supported, is that correct?

**Comment by adujardin** [comment]
That's correct, the ZED SDK 2.8 only supports CUDA up to 10.0. The next release will support 10.1
