### ISSUE TITLE
Get imu data from svo file

### ISSUE THREAD

**Issue by shentaowang** [stereolabs/zed-python-api#116]
Hello，

When I use zed sdk 2.8.4, can I get imu data from svo file through python api?

The python api description is as follows:
In SVO reading mode, the TIME_REFERENCE_CURRENT is currently not available (yielding :data:`~pyzed.sl.ERROR_CODE.ERROR_CODE_INVALID_FUNCTION_PARAMETERS`. Only the quaternion data at TIME_REFERENCE_IMAGE is available. Other values will be set to 0.

Although this seems impossible, but I want to ask who has a solution？

**Comment by adujardin** [comment]
Hi,
Unfortunately, the SVO only contains the quaternion (image sync) and not the raw IMU data currently.
There is no easy solution. You could record the raw IMU data in a CSV file by yourself alongside the SVO recording, and read it back with manual synchronization.
