### ISSUE TITLE
libsl_core.so Error ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [stereolabs/zed-python-api#122]
i get this error everytime i try to import the ```pyzed.sl``` module

```
libsl_core.so: cannot open shared object file: No such file or directory
```

**Comment by Poutsh** [comment]
Hi @MohamedAliRashad ,

Can you tell me which version of the ZED SDK are you using?

**Comment by MohamedAliRashad** [comment]
@Poutsh 
ZED SDK 3.0 with cuda 10.2

**Comment by Poutsh** [comment]
@MohamedAliRashad 

Have you rebuilt/reinstalled the ZED Python API after you installed ZED SDK 3.0?
Can you give me the output of :
```
ls /usr/local/lib/python3.6/dist-packages/pyzed*
```
Replace python3.6 with your version of python 3

**Comment by MohamedAliRashad** [comment]
@Poutsh 
Nothing Changed.
Here is the output
![Screenshot from 2020-01-27 13-17-50](https://user-images.githubusercontent.com/26205298/73170590-7d3dcc80-4107-11ea-9110-ddec9470576d.png)

**Comment by Poutsh** [comment]
Is there a ```/usr/local/zed_previous``` directory in your system?
Can you delete it and rebuild/reinstall the python wrapper ?

**Comment by MohamedAliRashad** [comment]
@Poutsh 
Still not working

**Comment by Poutsh** [comment]
@MohamedAliRashad 
It looks like there is a pyzed compiled with SDK 2.8 that is present on your system (libsl_core.so was removed in 3.0)

You can install "locate" on Ubuntu to search for pyzed installs that can produce this behavior :
```shell
sudo apt-get install locate
sudo updatedb
locate pyzed
```

**Comment by MohamedAliRashad** [comment]
@Poutsh 
you were correct
![Screenshot from 2020-01-28 19-48-21](https://user-images.githubusercontent.com/26205298/73290480-30411f80-4207-11ea-8cea-152b64dad4c8.png)

How to remove them ?
i tried ```sudo python3 setup.py cleanall``` but it only removed the 3.0 files

**Comment by Poutsh** [comment]
@MohamedAliRashad 
You can remove those files using the rm command
```
rm -rf .local/lib/python3.6/site-packages/pyzed
rm -rf .local/lib/python3.6/site-packages/pyzed-2.8.dist-info
```

**Comment by MohamedAliRashad** [comment]
@Poutsh 
I had to use the sudo command because of this error
![Screenshot from 2020-01-29 12-10-33](https://user-images.githubusercontent.com/26205298/73347566-7e4e3580-4290-11ea-9982-7c21ac33a50f.png)

**Comment by Poutsh** [comment]
@MohamedAliRashad 
Yes without the --user option you have to use sudo.
Have your problem been solved ?

**Comment by MohamedAliRashad** [comment]
@Poutsh 
Yes, Thanks Alot.
