### ISSUE TITLE
TypeError: Argument 'detection_confidence_threshold' has incorrect type (expected bool, got int)

### ISSUE THREAD

**Issue by jackkwok** [stereolabs/zed-python-api#128]
On the Jetson Xavier (Jetpack 4.2), I got below TypeError error when trying to run Tutorial 6. I have ZED SDK 3.0.1 and ZED 2.0 device.  I built the python ZED sdk from source.  Any idea?

$ python3 object_detection.py
[ZED][Init] Depth mode: PERFORMANCE
[ZED][Init] Video mode: HD720@60
Object Detection: Loading Module...
Traceback (most recent call last):
  File "object_detection.py", line 99, in <module>
    main()
  File "object_detection.py", line 63, in main
    obj_runtime_param.detection_confidence_threshold = 40
TypeError: Argument 'detection_confidence_threshold' has incorrect type (expected bool, got int)

**Comment by adujardin** [comment]
It's a bug from the python wrapper, we'll commit a fix
