### ISSUE TITLE
supporting ZED SDK 3.2 (CUDA 10.2,SDK 3.2)

### ISSUE THREAD

**Issue by ryota2425** [stereolabs/zed-python-api#148]
Im using Jetson xavier NX.
Will you provide support for SDK 3.2?
Thank you.

**Comment by harshilpatel** [comment]
same for CUDA 9.0 SDK < 3

**Comment by adujardin** [comment]
The NX on 3.2 is supported, there was an issue in the script packaged in the installer for the JP44 at the release, but it's now fixed.

You can download this script to get the whl file. All recent supported platform should be handled :

```sh
# Redownload the script just in case, but should already be present
wget download.stereolabs.com/zedsdk/pyzed -O /usr/local/zed/get_python_api.py
python3 /usr/local/zed/get_python_api.py
```

@harshilpatel For older 2.X version you should check this release https://github.com/stereolabs/zed-python-api/releases/tag/v2.8.x

**Comment by ryota2425** [comment]
I redownloaded this file and it all worked all. Appreciate the help here.
