### ISSUE TITLE
Why my depth viewer's result is so bad?

### ISSUE THREAD

**Issue by Wei10857104** [stereolabs/zed-python-api#152]
![image](https://user-images.githubusercontent.com/69885789/90608282-f54f1980-e234-11ea-965d-3672b4fdd7c2.png)

This is my depth viewer's result.

But I want to get like this result.

![image](https://user-images.githubusercontent.com/69885789/90608431-36dfc480-e235-11ea-8d2e-f7a03580cfb1.png)

Is the reason for these completely different results that environment indoor or outdoor?

**Comment by qt-truong** [comment]
Hi @Wei10857104,

You can try to change the settings of your viewer, in particular the sensing mode (Fill/Standard) and the confidence/texture confidence (set to maximum values if you don't want any filtering)
