### ISSUE TITLE
Wrong Documentation: https://www.stereolabs.com/docs/positional-tracking/coordinate-frames/

### ISSUE THREAD

**Issue by dige-dev** [stereolabs/zed-python-api#158]
We have been unable to set the world frame on any of our ZED cameras. We suspect that the example provided in the example at: https://www.stereolabs.com/docs/positional-tracking/coordinate-frames/ is outdated.
Here is what we have tried below:

        self.initialPosition = sl.Transform()
        translation=sl.Translation(-0.081 0.093 0.303)
        orientation=sl.Orientation(-0.017,0.717,-0.095, 0.069)
        self.initialPosition.set_translation(translation)
        self.initialPosition.set_orientation(orientation)
        a = self.initialPosition.get_orientation

Please advise

**Comment by qt-truong** [comment]
Hi @dige-dev,

Indeed the example code is misleading, thanks for pointing it out. We are going to fix that.
Translation and orientation vectors are actually not set that way. Here is what you could do instead :
```python
self.initialPosition = sl.Transform()
translation = sl.Translation()
translation.init_vector(-0.081,0.093,0.303)
orientation = sl.Orientation()
orientation.init_vector(-0.017,0.717,-0.095, 0.069)
self.initialPosition.set_translation(translation)
self.initialPosition.set_orientation(orientation)
```

You can find more documentation on ZED SDK here : https://www.stereolabs.com/docs/api/python/

**Comment by dige-dev** [comment]
Thank you!
