### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Shishir-Kumar-Singh** [stereolabs/zed-python-api#164]
I am getting this error at the time of importing pyzed library in python sample program..
python positional_tracking.py 
Illegal instruction (core dumped)

SDK version : 3.3
Device: Jetson with jetpack 4.4

**Comment by raman123456789** [comment]
i am aswell getting the same error, could you please share how did you solved it.

**Comment by Shishir-Kumar-Singh** [comment]
@raman123456789 What is your configuration...can you elaborate please like SDK version, OS and the exact problem scenario because this issue come up generally because of lib issues.

**Comment by qt-truong** [comment]
Hi @raman123456789,

Can you check [this answer](https://github.com/stereolabs/zed-python-api/issues/167#issuecomment-784050030) and see if it helps with your issue ?

**Comment by wasdee** [comment]
> Hi @raman123456789,
> 
> Can you check [this answer](https://github.com/stereolabs/zed-python-api/issues/167#issuecomment-784050030) and see if it helps with your issue ?

this is working for me.

Jetpack 4.6.1
