### ISSUE TITLE
Location of zed calibration file

### ISSUE THREAD

**Issue by saratrajput** [stereolabs/zed-python-api#166]
I'm launching zed camera from within docker. The zed calibration file is downloaded every time a new docker container is launched. Instructions at [link1](https://support.stereolabs.com/hc/en-us/articles/360007497173-What-is-the-calibration-file-) and [link2](https://www.stereolabs.com/developers/calib/) mention to place the calibration file in ```/usr/local/zed/settings/``` directory. I'm wondering if there is a way to place the the calibration file in the repository itself and specify the location with Python API?

**Comment by adujardin** [comment]
It is indeed in `/usr/local/zed/settings/` by default, but in the docker container, it is wiped at each launch.

You can either mount a volume like `docker run -v /usr/local/zed/settings/:/usr/local/zed/settings/ ....`

Or you can specify in the InitParameters a different settings path ([API doc](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1InitParameters.html#ac3230b880fb396efb42c0f9febcd4c10))

```python
import pyzed.sl as sl

zed = sl.Camera()

init_params = sl.InitParameters()
init_params.optional_settings_path = "/custom/folder"

err = zed.open(init_params)
```
