### ISSUE TITLE
Get 3d point cloud calculation issues

### ISSUE THREAD

**Issue by afloralblb** [stereolabs/zed-python-api#168]
Hi,

I have two questions:

1. I am trying to use the depth map as an input of some algorithms and use the output depth map to get 3d point cloud, so i need to calculate the 3d point cloud manually. I checked 'SN****.conf' file, i only found cx,cy,fx,fy but i cannot find the scaling factor, is it contained in 'SN****.conf' file?

2. Currently I got 8-bit depth map which scales in [0,255], is it possible to using such kind of depth map to get 3d point cloud manually or i have to use depth_map.getValue(x,y) to get raw depth value to do calculation? 

Thanks

**Comment by obraun-sl** [comment]
Duplicated with https://github.com/stereolabs/zed-examples/issues/346
