### ISSUE TITLE
Build setup.py issues

### ISSUE THREAD

**Issue by afloralblb** [stereolabs/zed-python-api#169]
Hi,
Ubuntu: 16
Python: 3.6
CUDA: 10.2
ZED SDK: 3.4

I have installed ZED SDK successfully and try to build setup.py but i have some errors "compiler_compat/ld: cannot find -lusb-1.0", any suggestions on how to solve this? 

ZED SDK Version: OK
compilation flags: ['-std=c++14', '-Wno-reorder', '-Wno-deprecated-declarations', '-Wno-cpp', '-O3']
include dirs: ['/home/fanyun/anaconda3/envs/experiments/lib/python3.6/site-packages/numpy/core/include', '/usr/local/zed/include', '/usr/local/cuda/include']
library dirs: ['/home/fanyun/anaconda3/envs/experiments/lib/python3.6/site-packages/numpy/core/include', '/usr/local/zed/lib', '/usr/local/cuda/lib64']
libraries: ['sl_zed', 'usb-1.0']
Building module: ('pyzed.sl', ['pyzed/sl.pyx'])
running build
running build_py
running build_ext
building 'pyzed.sl' extension
gcc -pthread -B /home/fanyun/anaconda3/envs/experiments/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./pyzed -I/home/fanyun/anaconda3/envs/experiments/lib/python3.6/site-packages/numpy/core/include -I/usr/local/zed/include -I/usr/local/cuda/include -I/home/fanyun/anaconda3/envs/experiments/include/python3.6m -c pyzed/sl.cpp -o build/temp.linux-x86_64-3.6/pyzed/sl.o -std=c++14 -Wno-reorder -Wno-deprecated-declarations -Wno-cpp -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/fanyun/anaconda3/envs/experiments/compiler_compat -L/home/fanyun/anaconda3/envs/experiments/lib -Wl,-rpath=/home/fanyun/anaconda3/envs/experiments/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pyzed/sl.o -L/home/fanyun/anaconda3/envs/experiments/lib/python3.6/site-packages/numpy/core/include -L/usr/local/zed/lib -L/usr/local/cuda/lib64 -Wl,-R/home/fanyun/anaconda3/envs/experiments/lib/python3.6/site-packages/numpy/core/include -Wl,-R/usr/local/zed/lib -Wl,-R/usr/local/cuda/lib64 -lsl_zed -lusb-1.0 -o build/lib.linux-x86_64-3.6/pyzed/sl.cpython-36m-x86_64-linux-gnu.so
/home/fanyun/anaconda3/envs/experiments/compiler_compat/ld: cannot find -lusb-1.0
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

Thanks!

**Comment by adujardin** [comment]
The ZED SDK installer should have installed it for you I think, but you can manually install it since you seem to be on Ubuntu with something like this:

```
sudo apt install libusb-1.0-0-dev
```
