### ISSUE TITLE
Possible to pre-process images in ZED pipeline

### ISSUE THREAD

**Issue by silent-code** [stereolabs/zed-python-api#170]
Hi is it possible to pre-process images in the ZED pipeline after the video image is acquired on the ZED hardware but prior to the ZED algorithms such as spatial mapping, SLAM, etc. The reason for this is to adjust for environmental factors such as haze, low lighting etc. 

Thanks in advance.

**Comment by adujardin** [comment]
Hi,
Yes it is possible to change some camera settings using the API, here is the list: https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1VIDEO__SETTINGS.html

[This sample](https://github.com/stereolabs/zed-examples/tree/master/camera%20control) shows how to use them.
