### ISSUE TITLE
Shutter speed

### ISSUE THREAD

**Issue by RenanGeorgio** [stereolabs/zed-python-api#180]
Anyone know how to tell me what are the real values ​​of shutter speed of the camera?

At least the range? MIN shutter speed and MAX shutter speed?

Zed only provide de scale from 1-100

**Comment by adujardin** [comment]
Duplicate from https://github.com/stereolabs/zed-ros-wrapper/issues/717

If someone stumbles upon this later, here's the same answer with an example:

The exposition time mapping is depending on the framerate.

15fps setExposure(100) -> 19.97ms
30fps setExposure(100) -> 19.97ms
60fps setExposure(100) -> 10.84072ms
100fps setExposure(100) -> 10.106624ms

Special case for the setExposure(0) that always corresponds to 0.17072ms

The exposition is mapped linearly in a percentage of the max value above (plus the minimum value of 0.17072ms), ex:

_15fps setExposure(37) -> 19.97*0.37 + 0.17072 = 7.56ms_
