### ISSUE TITLE
 How to customize the object detection model

### ISSUE THREAD

**Issue by leeisack** [stereolabs/zed-python-api#181]
Hi I'm working on a project and I'm using 3d object detection in the tutorial. However, I want to make it recognize objects other than the model here. Can you tell me how to customize the object model?

**Comment by adujardin** [comment]
Hi
The model can't be customized currently, we plan to add an input to detect/track objects in 3D from a custom model in a future version of the SDK. In the meantime, you can use something like yolov5 https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data or darknet https://github.com/AlexeyAB/darknet to detect custom objects
