### ISSUE TITLE
import error cannot import video camera from camera

### ISSUE THREAD

**Issue by omu34** [stereolabs/zed-python-api#184]
help with codes

**Comment by qt-truong** [comment]
Hi @omu34,

Could you please specify your problem in more detail so that we can help you ? 
Thanks in advance.

**Comment by omu34** [comment]
the problem is that the Html page shows only the icon of the images and
video but don't show the real image and video

**Comment by qt-truong** [comment]
Thanks for getting back to us. I am sorry but I am not sure I understand your problem. 
Have you successfully managed to install the ZED SDK/Python API ? Are you trying to run a sample code ? 

I suggest you to visit our tutorial repository ([link](https://github.com/stereolabs/zed-examples/tree/master/tutorials)), this will guide you through your first steps with your camera.
