### ISSUE TITLE
What is different between MEASURE.DEPTH and VIEW.DEPTH ?

### ISSUE THREAD

**Issue by KyuminHwang** [stereolabs/zed-python-api#187]
I want to get depth map through ZED camera

So, I am referring to the depth viewer and the sample code from https://github.com/stereolabs/zed-opencv/blob/master/python/zed-opencv.py.

However, the difference between the depth map (VIEW.DEPTH) and the saved depth map (MEASURE.DEPTH) seen in the depth viewer is too large. 

VIEW.DEPTH does color rendering, can you explain exactly what kind of work you do?
What is the problem?

![depth](https://user-images.githubusercontent.com/37618036/126061357-f0594a77-18aa-428f-a5ae-4496f591c734.png) using **MEASURE.DEPTH**.

![depth1](https://user-images.githubusercontent.com/37618036/126061370-407995b0-1457-47e9-8945-d9fdd4ab6f03.png) using **VIEW.DEPTH**.

**Comment by Myzhar** [comment]
`measure.depth` contains the depth values in floating point type. OpenCV converts them to a visualizable value before displaying.
`view.depth` does not contain depth values, but their normalized values in the range (0,255) to be rendered on screen.

**Comment by KyuminHwang** [comment]
@Myzhar Thank you for timely response ! 👍 

You means that **view.depth** isn't contain any depth information? Then how display like depth map?
My guess is that I convert the RGB image to a GRAY Scale image, and arbitrarily normalize it to the [0,255] interval, is this a valid estimate?

The result of **VIEW.DEPTH** looks very similar to the depth map, so it feels like a visualization by estimating the depth information.

Could you please tell me which part of the code the library is?
(Then I will be able to clearly understand the rendering operation principle of **VIEW.DEPTH**.)

**Comment by Myzhar** [comment]
`view.depth` is indeed the result of the normalization of `measure.depth`, mapping the values [0,max_range] -> [0,255].
The white pixels that you see while displaying `measure.depth` are relative to pixels with no depth information, so Nan or Inf.

**Comment by KyuminHwang** [comment]
@Myzhar Thank you for comment 👍
