### ISSUE TITLE
How to change the visual field of the camera?

### ISSUE THREAD

**Issue by pilot00** [stereolabs/zed-python-api#189]
Hi,

I think the field of view of the camera is too large, how can I adjust it to meet my needs for different field of view sizes?

Many thanks!

**Comment by obraun-sl** [comment]
Hi,
You cannot change the field of view of the camera since it's a fixed focal length. 
However, you can change the resolution of the camera (HD720,HD1080, HD2K) which will change internally the field of view of the camera : 
--> in terms of FoV : HD1080 < HD2K < HD720
