### ISSUE TITLE
Object detection with ZED2i camera

### ISSUE THREAD

**Issue by dohyeonYoon** [stereolabs/zed-python-api#194]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I see the explanation that I can detect the custom object with ZED2i camera 
![tttt](https://user-images.githubusercontent.com/66056440/135975356-de483aaa-4f04-4c0f-9fa2-c65fe2ead70a.PNG)

but I can't find the way the detect custom object with python code. 

how can i do that ? 

thank you 

### Steps to Reproduce

1.
2.
3.
....

### Expected Result

.

### Actual Result

.

### ZED Camera model

ZED2i

### Environment

```shell
os: window 10 and ubuntu 18.04
cpu: intel-i7
sdk: latest
```

**Comment by Myzhar** [comment]
Hi @dohyeonYoon 
the "custom object" feature will be available with the release v3.6 of the SDK.

Please use Github issues only to report bugs, the next time you have a question please post it on our [Community forum]([url](https://community.stereolabs.com/)).
