### ISSUE TITLE
the object detection and body tracking is not working with zed camera on jetson xavier

### ISSUE THREAD

**Issue by elnou** [stereolabs/zed-python-api#217]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi,

I tried to run the object detection and body tracking from the zed-examples part on jetson xavier but none of them is working, this is the error I am getting: 
"[Sample][Error] enable Object Detection  | MODULE NOT COMPATIBLE WITH CAMERA : The object detection module is not compatible with the ZED 
Exit program.
"

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Expected result was that both body tracking and object detection examples working

### Actual Result

[Sample][Error] enable Object Detection  | MODULE NOT COMPATIBLE WITH CAMERA : The object detection module is not compatible with the ZED 
Exit program.

### ZED Camera model

ZED

### Environment

```shell
OS: ubuntu 20.04 
CPU: ARM
GPU: Nvidia Jetson Xavier
```

**Comment by obraun-sl** [comment]
Hi,
Currently the Object detection module is only working with ZED-M , ZED2 and ZED2i (as it requires IMU inside). It does not work with the ZED.
