### ISSUE TITLE
Can't build plugin, Error: you must install Cuda

### ISSUE THREAD

**Issue by keli95566** [stereolabs/zed-python-api#221]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I can't install this plugin no matter what. 

First, it can not find cuda when running: ```python get_python_api.py```

-> Downloading to 'C:\Users\keli9\Code'
Detected platform:
         win
         Python 3.7
         ZED SDK 3.8
-> Checking if https://download.stereolabs.com/zedsdk/3.8/whl/win/pyzed-3.8-cp37-cp37m-win_amd64.whl exists and is available
Error downloading whl file (HTTP Error 403: Forbidden)

Unsupported platforms, no pyzed file available for this configuration
 It can be manually installed from source https://github.com/stereolabs/zed-python-api

Then, I try to build from source, it outputs error saying cuda must be installed

Error: you must install Cuda.
compilation flags:
include dirs:
library dirs:
libraries:
Building module: ('pyzed.sl', ['pyzed/sl.pyx'])
running build
running build_py
running build_ext
building 'pyzed.sl' extension
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I.\pyzed -IC:\Users\keli9\anaconda3\envs\zed\include -IC:\Users\keli9\anaconda3\envs\zed\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /EHsc /Tppyzed/sl.cpp /Fobuild\temp.win-amd64-cpython-37\Release\pyzed/sl.obj
sl.cpp
C:\Users\keli9\Code\NERFUnity\zed-python-api\src\pyzed\Utils.cpp(33): fatal error C1083: Cannot open include file: 'sl/Camera.hpp': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

### Steps to Reproduce

Clone this repository, create a conda environment, and try to build from source or download the python api

### Expected Result

Should be able to detect cuda and build

### Actual Result

Can not build 

### ZED Camera model

ZED Mini

### Environment

```shell
OS:Windows 10
CUDA 11.7 is installed and is on the path
Python 3.7 via a conda environment
ZED SDK 3.8

( The installer mentioned that it is the correctly matched version: ZED_SDK_Windows10_cuda11.7_v3.8.1.exe)
```

**Comment by braoutch** [comment]
Hello, get_python_api currently has an issue on windows. It will be fixed in 3.8.2 which will be out very soon.
