### ISSUE TITLE
Solution for "No module named 'pyzed.camera'"

### ISSUE THREAD

**Issue by sczhou** [stereolabs/zed-python-api#50]
Win10: build & install are OK.
pyzed can be imported, but importing pyzed.* is failed.
The following solution may be useful (It works for me):
1. move the setup.py to pyzed folder.
2. change something in setup.py(delete the 'pyzed\' and change 'py_packages = ["."]' and 'package_data = {"." : ["*.pxd"]}').
3. build and install again.

**Comment by zebediz** [comment]
Possibly just make sure you're in the pyzed directory and try running python and import again.
