### ISSUE TITLE
MEM_GPU option didn't  work?

### ISSUE THREAD

**Issue by mohhao** [stereolabs/zed-python-api#53]
Hey man,
    Thanks for your working!
    In function retrieveMeasure,option core.PyMEM.PyMEM_GPU didn't work?

**Comment by Poutsh** [comment]
Hi @mohhao .
It would be nice to describe your problem more but here is how you use a PyMat with PyMEM_GPU and retrieve_measure in or python wrapper : 

```c++
depth_gpu = core.PyMat()
depth_gpu.init_mat_type(width, height, core.PyMAT_TYPE.PyMAT_TYPE_32F_C1, core.PyMEM.PyMEM_GPU)
while i < 50 : 
    if (zed.grab(runtime_parameters) == tp.PyERROR_CODE.PySUCCESS) : 
        zed.retrieve_measure(depth_gpu, sl.PyMEASURE.PyMEASURE_DEPTH, core.PyMEM.PyMEM_GPU)

#Don't forget to free your gpu mat before closing the camera
depth_gpu.free(core.PyMEM.PyMEM_GPU)
zed.close()
```

I hope this will help you to solve your problem.
