### ISSUE TITLE
Cannot convert 'Rotation' to Python object

### ISSUE THREAD

**Issue by Nadamani** [stereolabs/zed-python-api#61]
Hi, 
I'm stucking with this issue when I try to build the plugin : "python setup.py build" any recommandation ? 
![issue](https://user-images.githubusercontent.com/45818226/49865123-62759f00-fe04-11e8-9cc4-8566b5d6d0af.png)

**Comment by Poutsh** [comment]
Hi @Nadamani 

Indeed there seems to be some problems with some deprecated code that needs to be fixed, however this should only happen if you call these functions at runtime, not when you build/install it with the readme instructions.

Can I ask you how you built your module or at least the full log of your problem so we can fix everything? Please tell me what is your ZED SDK version and if you cloned the python wrapper from master or downloaded a release.

Thank you in advance!
