### ISSUE TITLE
my python can not find the pyzed.s1 model.

### ISSUE THREAD

**Issue by k98732142** [stereolabs/zed-python-api#65]
I use anaconda3 to create the environment "py36" and i also success to use 'python setup.py build' and 'python setup.py install'.
But my python can not find the pyzed.s1 model.
![default](https://user-images.githubusercontent.com/43366122/50403990-07698200-07de-11e9-9f41-5f5343123770.PNG)

**Comment by Poutsh** [comment]
Hi @k98732142 

I think you have made a typo here. It's not pyzed.s1 but pyzed.sl, but you seem to have wrote that in your code on your screenshot.
Have you installed the module using pip like said in the README? If you are using Anaconda, it'll be in a totally different path and will not work, you should try without it.

**Comment by k98732142** [comment]
@Poutsh  Yes....I write the wrong model name. Thanks you for your help.
