### ISSUE TITLE
Spatial Mapping with ZEDm using the Pyhton API

### ISSUE THREAD

**Issue by nalinraut** [stereolabs/zed-python-api#70]
I tried the spatial mapping example using the Python API, however, there seems something wrong with code since it exits at the enabling stage. For more details have a look below at the snippets.

![issue](https://user-images.githubusercontent.com/33768644/51846587-c6e7b180-2311-11e9-8a50-1f6c24eb7adc.png)

![issue_result](https://user-images.githubusercontent.com/33768644/51846604-d23add00-2311-11e9-92bc-f4141ff383bd.png)

**Comment by Poutsh** [comment]
Hi @nalinraut 

Can I ask you what is the ZED SDK version you're using and on which platform you're running that program?

**Comment by nalinraut** [comment]
@Poutsh I am using ZED SDK 2.7 on TX2. Using python3. I get 'FAILURE' as error when i print it.

**Comment by nalinraut** [comment]
`import pyzed.sl as sl

def main():
    zed = sl.Camera()
    init_params = sl.InitParameters()
    init_params.sdk_verbose = True
    err = zed.open(init_params)
    print(repr(err))
    zed.close()

if __name__ == "__main__":
    main()`

**Comment by KevinGriffin31** [comment]
Also having this same issue has anything new been found out about it?

**Comment by KevinGriffin31** [comment]
@adujardin after running the code you posted I get a similar output as @nalinraut got, however, I am missing a line. 
I got:

ZED (Init) >> Depth mode: PERFORMANCE
ZED (Init) >> Video mode: HD720@60
SUCCESS

**Comment by adujardin** [comment]
You can display the error code information to know more, something like this: 
```python
err = zed.enable_spatial_mapping(mapping_parameters)
if err != sl.ERROR_CODE.success:
	print(repr(err))
```

**Comment by KevinGriffin31** [comment]
The above code only returned "FAILURE"
