### ISSUE TITLE
Change RuntimeParameters 

### ISSUE THREAD

**Issue by zaher88abd** [stereolabs/zed-python-api#71]
I would ask how to change the RuntimeParameters from standard to FILL. Also, how to change MaxRange and Confidence? The same you do in the Depth View.

**Comment by rishabh700** [comment]
How did you specify the confidence threshold values?

**Comment by zaher88abd** [comment]
This how you cold set the confidence:
``` 
zed = sl.Camera()
zed.set_confidence_threshold()
```
You could check the comment of the [funcation](https://github.com/stereolabs/zed-python-api/blob/50cdaba3412924c957d607d2fdaa022f241d8b81/pyzed/sl.pyx#L5473).
