### ISSUE TITLE
image.get_data() not able to detect object

### ISSUE THREAD

**Issue by zkumar** [stereolabs/zed-python-api#74]
when I am passing image.get_data() to my object detection API (based on yolo3).  Function is return all empty values. For now, I am storing data and retrieving the data again and passing it to algorithm. This way it is able to detect the object. What is the difference in data? snippet of working code is below. Any suggestion?

   zed.retrieve_image(image, sl.VIEW.VIEW_LEFT) # Retrieve left image
      #cv2.imshow('ZED', image.get_data())
      cv2.imwrite('TestZed.jpg', image.get_data(), [int(cv2.IMWRITE_JPEG_QUALITY), 100])
      # read input image
      savedimage = cv2.imread('testzed.jpg')
              # apply object detection
      bbox, label, conf = cv.detect_common_objects(savedimage)

**Comment by Poutsh** [comment]
Hi @zkumar ,

Have you opened your zed camera correctly using open and used the grab function before the retrieve?
You can see an example on how to retrieve the image and store it in an opencv matrix here : [examples/live_camera.py](https://github.com/stereolabs/zed-python-api/blob/master/examples/live_camera.py) .
Also, you seem to have different names for the file you saved (TestZed.jpg) and the one you read for object detection (testzed.jpg)

Please tell me if that fixed your problem.
