### ISSUE TITLE
Does Vuforia support ZED camera?

### ISSUE THREAD

**Issue by KHBHH** [stereolabs/zed-python-api#75]
Hi,

I am using AR camera in my Unity project (I have Vuforia package), I want to set the camera as ZED camera, does Vuforia support ZED? 

And how can I disable one of the lans for ZED camera?

Thanks,
Karni

**Comment by ckorris** [comment]
Unfortunately, Vuforia does not support the ZED SDK. 

It technically supports the ZED, but only by using it as a basic video device, and connecting directly to it. The images are unrectified, with both left and right images together (SBS) and there is no depth information. And as you can only have one active connection to the ZED at a time, it is not possible to have Vuforia _and_ the ZED SDK connected to the camera at once as a workaround. 

That said, Vuforia recently responded to [a post of mine](https://developer.vuforia.com/forum/unity/changing-webcamtexture) asking about this on their forums in the context of their Unity plugin. They said there is now an [External Camera](https://library.vuforia.com/content/vuforia-library/en/articles/Solution/external-camera.html) feature that may work, as you can pass custom camera frames to the SDK. We haven't tested this ourselves, and they say it may not be ideal as it was developed for mobile and UWP, but worth investigating.
