### ISSUE TITLE
Lossless vs Raw Compression for SVO Recording

### ISSUE THREAD

**Issue by PNeigel** [stereolabs/zed-python-api#83]
Less of an issue and more of a question:

Is the **lossless** compression for SVO recording guaranteed to give the exact same pixel values for every image compared to the **raw** compression mode?

**Comment by adujardin** [comment]
In short yes (that would be a bug otherwise). Please note however that the raw mode is deprecated and lack some features. It could be removed in future versions.

**Comment by PNeigel** [comment]
Thank you very much for the quick answer. I guess that's why raw is only available over the API and not in e.g. the ZED SDK explorer.
