### ISSUE TITLE
ModuleNotFoundError (No module named pyzed)

### ISSUE THREAD

**Issue by Sakuyal** [stereolabs/zed-python-api#85]
Just installed this package using pip and it keeps giving me this error. I've tried uninstalling and reinstalling, both from pip and the source itself, to no avail. With other packages I also installed them through pip and they worked just fine. So what's up?

**Comment by Sakuyal** [comment]
Nevermind, I'm silly. Was defaulting to the wrong version of python.

**Comment by pmc492** [comment]
Hello [Sakuyal](https://github.com/Sakuyal), which python version are you using?
