### ISSUE TITLE
How to extend the distance of depth_sensing ?

### ISSUE THREAD

**Issue by Jackyiyo** [stereolabs/zed-python-api#90]
Hello ,
I follow the code below to get the point cloud value and calculate the Euclidean distance: 
https://github.com/stereolabs/zed-python-api/blob/master/tutorials/depth_sensing.py

But I found some problems in my experiment:
(1) My results is not accurate. The ground truth distance between camera and object is 4 meters, But the Euclidean distance measure by the ZED is just 3 meters. There is a lot of errors in distance measurement. How should I solve this kind of problem?
(2) The depth_sensing code seems cant measure the object which is far more than 4 meters. For each objects which ground truth distance is more than 4 meters, the Euclidean distance measure by ZED is  only 4 meters.(For example, I measure the ground truth distance between camera and object is 6 meters,but the ZED point cloud Euclidean distance is only 4 meters). Which parameter should I adjust to avoid this kind problem and to extend the measure distance of depth_sensing.py? 

thanks

**Comment by rishabh700** [comment]
Probably you can change some settings like changing:
1. Depth range (min, max depth), 
2. Depth mode to Ultra. 
More info can be found here: https://www.stereolabs.com/docs/depth-sensing/advanced-settings/
