### ISSUE TITLE
ImportError: libhidapi-libusb.so.0 

### ISSUE THREAD

**Issue by Muthukumar-S1979** [stereolabs/zed-python-api#95]
I have my ZED camera connected and i have installed ZED SDK with this script "ZED_SDK_Ubuntu16_v2.8.3.run" for my ubuntu-v16.4.

Installation completed successfully , while i try to run the samples "live_camera.py" from  zed-python-api-master/examples
Am getting below error

Traceback (most recent call last):
  File "live_camera.py", line 27, in <module>
    import pyzed.sl as sl
ImportError: libhidapi-libusb.so.0: cannot open shared object file: No such file or directory

Seems libhidapi-libusd.so.0 drivers not installed properly from ZED SDK . Request to help me on this

**Comment by obraun-sl** [comment]
Hi,
You can install hidapi packet with : 
`$ sudo apt-get install libhidapi-dev` 

That will install the missing libraries.

**Comment by wangjunfeng90214** [comment]
When I try sudo apt-get install libhidapi-dev in Ubuntu 16.04, the terminal appears a picture like this:
![Screenshot from 2019-10-23 11-15-03](https://user-images.githubusercontent.com/20900567/67354262-45167300-f587-11e9-836f-9e00d8764731.png)

What should I do to next?

**Comment by obraun-sl** [comment]
Press Tab or your keyboard arrows so that the <OK> text is underligned. Then press OK.
