### ISSUE TITLE
ImportError: cannot import name 'VideoCamera'

### ISSUE THREAD

**Issue by srikanthk104** [stereolabs/zed-python-api#98]
Hello all i am facing issues in importing VideoCamera can anyone pls help me

from camera import VideoCamera not able to import it and endingup with issue as 
ImportError: cannot import name 'VideoCamera'

**Comment by Poutsh** [comment]
Hi @srikanthk104 

We have no class or module named VideoCamera, please take a look at the examples, to know how to use our python api : https://github.com/stereolabs/zed-python-api/tree/master/examples
