### ISSUE TITLE
how to install the plugin using pip on jetson TX2(Ubuntu 18 and ARM)

### ISSUE THREAD

**Issue by ridlwanhas** [stereolabs/zed-python-api#99]
if I refer to this link there is an install option on ubuntu 18 but for the processor arm there is no information about installing using pip.
can anyone inform the URL address for it?

**Comment by adujardin** [comment]
There's currently no pre-build version for aarch64, you have to build the plugin from source.
The instructions can be found [here](https://github.com/stereolabs/zed-python-api#build-the-plugin-from-source).

**Comment by ridlwanhas** [comment]
@adujardin many thank's for u'r information.
